#Application configuration
server:
  port: 8080

#To See H2 Console in Browser:
#http://localhost:8080/h2-console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

  sql:
    init:
      platform: myh2
      username: sa
      password: 123


      #====================================
      #JPA / HIBERNATE
      #====================================

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"